### ISSUE TITLE
Error when using BeOfCase on a struct discriminated union with shared fields

### ISSUE THREAD

**Issue by Numpsy** [cmeeren/Faqt#10]
Hi,

I was having a go at making some struct discriminated unions use shared/unnamed fields as described at https://learn.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-9#field-sharing-for-struct-discriminated-unions in .NET 9 and hit an error in my unit tests.

Say I have a discriminated union like
```fsharp
    [<Struct>]
    type MyStructDu =
        | Field1 of string
        | Field2 of string
```

If I have a unit test on the first case like
```fsharp
    [<Fact>]
    let ``Struct DU case one`` () =
        let f1 = Field1 "F1"
        f1.Should().BeOfCase(Field1)
```

then it works ok, but for the second case, e.g
```fsharp
    [<Fact>]
    let ``Struct DU case two`` () =
        let f2 = Field2 "F2"
        f2.Should().BeOfCase(Field2)
```

Then i get 
```
System.ArgumentException : This is not a valid tuple type for the F# reflection library. (Parameter 'types')
```

```
FSharpType.MakeTupleType(Type[] types) line 1148
makeCaseTupleTypeCached@60.Invoke(UnionCaseInfo unionCaseInfo) line 61
memoizeRefEq@32-1.Invoke(a delegateArg0)
ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
memoizeRefEq@32.Invoke(a a) line 32
MakeCaseTupleTypeCached.Static(UnionCaseInfo unionCaseInfo) line 79
inner@26.Invoke(FSharpExpr expr) line 41
UnionAssertions.BeOfCase[a,b](Testable`1 t, FSharpExpr`1 caseConstructor, FSharpOption`1 because) line 47
BeOfCase.Struct DU case two() line 36
```

**Comment by cmeeren** [comment]
Thanks for the report. Seems to be an upstream issue. I created https://github.com/dotnet/fsharp/issues/18121.

**Comment by Numpsy** [comment]
Thanks

**Comment by cmeeren** [comment]
Workaround here: https://github.com/dotnet/fsharp/issues/18121#issuecomment-2531361845

Closing as it's an upstream issue.

**Comment by cmeeren** [comment]
Fixed upstream.

When a new SDK and FSharp.Core is released with this fix, both of the following must be true in order for the fix to apply:

- The runtime FSharp.Core version must contain the fix
- The project containing the DU must be compiled with an SDK/compiler that contains the fix
